FROM ubuntu:20.04

# Copying the script that installs packages
COPY install_packages.sh /home/

# Making the script executable
RUN chmod +x /home/install_packages.sh

# Running the script to install packages
RUN /home/install_packages.sh

# Copying the get_video_streamed script
COPY get_video_streamed.py /home/

# Making the script executable
RUN chmod +x /home/get_video_streamed.py

CMD ["bash"]
